name: Build Standalone App

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build standalone app
        run: |
          npx pkg . --targets node20 --output dist/ScreenTime
        shell: bash

      - name: List artifacts
        run: if [ "${{ matrix.os }}" = "windows-latest" ]; then dir dist/; else ls -alh dist/; fi
        shell: bash

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: dist/

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Download Ubuntu artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-ubuntu-latest
          path: ./dist-ubuntu

      - name: Download macOS artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-macos-latest
          path: ./dist-macos

      - name: Download Windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-windows-latest
          path: ./dist-windows

      - name: Verify artifacts presence
        run: |
          echo "Ubuntu artifacts:"
          ls -alh ./dist-ubuntu/
          echo "macOS artifacts:"
          ls -alh ./dist-macos/
          echo "Windows artifacts:"
          dir ./dist-windows/

      - name: Upload artifacts to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist-ubuntu/*
            ./dist-macos/*
            ./dist-windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
